# Elasticsearch Configuration

# Cluster name
cluster.name: elk-cluster

# Node name
node.name: node-1

# Network settings
network.host: 0.0.0.0
http.port: 9200

# Discovery settings
discovery.type: single-node

# Path settings
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch

# Memory settings
bootstrap.memory_lock: true

# Security settings
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: certs/elastic-certificates.p12

# HTTP SSL settings
xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.keystore.path: certs/elastic-certificates.p12
xpack.security.http.ssl.truststore.path: certs/elastic-certificates.p12

# Monitoring settings
xpack.monitoring.collection.enabled: true

# Audit settings
xpack.security.audit.enabled: true

# Index lifecycle management
xpack.ilm.enabled: true

# Cross-cluster replication (if needed)
# xpack.ccr.enabled: true

# Snapshot/Restore settings
path.repo: ["/var/lib/elasticsearch/snapshots"]

# Performance settings
indices.memory.index_buffer_size: 30%

# Heap size (uncomment and adjust if needed)
# ES_JAVA_OPTS: "-Xms4g -Xmx4g"

# Node roles (uncomment if you want to specify roles)
# node.roles: [ master, data, ingest ]

# Allow wildcard deletion (be cautious with this in production)
action.destructive_requires_name: false